package com.codexaa.repository;

import com.codexaa.model.OrderItem;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.util.List;

@Repository
public interface OrderItemRepository extends JpaRepository<OrderItem, Long> {

    // ── Basic finders ─────────────────────────────────────────────────────────

    List<OrderItem> findByOrderId(Long orderId);

    List<OrderItem> findByProductId(Long productId);

    // ── Store-scoped queries ──────────────────────────────────────────────────

    // All items sold across a store (for reporting)
    @Query("SELECT oi FROM OrderItem oi WHERE oi.order.store.id = :storeId")
    List<OrderItem> findByStoreId(@Param("storeId") Long storeId);

    // Items sold in completed orders only (for revenue reporting)
    @Query("SELECT oi FROM OrderItem oi " +
            "WHERE oi.order.store.id = :storeId " +
            "AND oi.order.status = 'COMPLETED'")
    List<OrderItem> findCompletedItemsByStoreId(@Param("storeId") Long storeId);

    // ── Stock / inventory queries ─────────────────────────────────────────────

    // Total quantity sold for a product across a store
    @Query("SELECT COALESCE(SUM(oi.quantity), 0) FROM OrderItem oi " +
            "WHERE oi.product.id = :productId " +
            "AND oi.order.store.id = :storeId " +
            "AND oi.order.status = 'COMPLETED'")
    Integer getTotalQuantitySoldByProduct(@Param("productId") Long productId,
                                          @Param("storeId") Long storeId);

    // ── Revenue queries ───────────────────────────────────────────────────────

    // Total revenue generated by a single product
    @Query("SELECT COALESCE(SUM(oi.lineTotal), 0) FROM OrderItem oi " +
            "WHERE oi.product.id = :productId " +
            "AND oi.order.store.id = :storeId " +
            "AND oi.order.status = 'COMPLETED'")
    BigDecimal getTotalRevenueByProduct(@Param("productId") Long productId,
                                        @Param("storeId") Long storeId);

    // ── Top products ──────────────────────────────────────────────────────────

    // Top N products by quantity sold — returns Object[]{productId, productName, totalQty, totalRevenue}
    @Query("SELECT oi.product.id, oi.productName, " +
            "SUM(oi.quantity), SUM(oi.lineTotal) " +
            "FROM OrderItem oi " +
            "WHERE oi.order.store.id = :storeId " +
            "AND oi.order.status = 'COMPLETED' " +
            "GROUP BY oi.product.id, oi.productName " +
            "ORDER BY SUM(oi.quantity) DESC")
    List<Object[]> findTopSellingProducts(@Param("storeId") Long storeId);

    // ── Existence / count ─────────────────────────────────────────────────────

    long countByOrderId(Long orderId);

    boolean existsByProductId(Long productId);
}